version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinemais
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/cinemais"
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  prisma-migrate:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/cinemais"
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run prisma:seed"
    depends_on:
      - postgres

volumes:
  postgres_data:
